// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goc.Api.Dtos
{
    public partial class ActionTypesDto
    {
        public int Id { get; set; }
        public string Type { get; set; }
    }
}