// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Goc.Business.Dtos;

namespace Goc.Api.Dtos
{
    public partial class Campaigns
    {
        public Campaigns()
        {
            Mission = new HashSet<MissionsDto>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }

        public virtual ICollection<MissionsDto> Mission { get; set; }
    }
}