// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Goc.Business.Dtos;

namespace Goc.Api.Dtos
{
    public partial class Messages
    {
        public int Id { get; set; }
        public int SenderTeam { get; set; }
        public int RecipientTeam { get; set; }
        public string Message { get; set; }
        public DateTime DateTime { get; set; }

        public virtual TeamsDto RecipientTeamNavigation { get; set; }
        public virtual TeamsDto SenderTeamNavigation { get; set; }
    }
}