// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goc.Api.Dtos
{
    public partial class Characters
    {
        public Characters()
        {
            ActionsLog = new HashSet<ActionsLog>();
            Evidences = new HashSet<Evidences>();
            TeamsCharacters = new HashSet<TeamsCharacters>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Story { get; set; }
        public string Attack { get; set; }
        public string Defense { get; set; }
        public string Bonus { get; set; }

        public virtual ICollection<ActionsLog> ActionsLog { get; set; }
        public virtual ICollection<Evidences> Evidences { get; set; }
        public virtual ICollection<TeamsCharacters> TeamsCharacters { get; set; }
    }
}