// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goc.Models
{
    public partial class ActionType
    {
        public ActionType()
        {
            ActionsLog = new HashSet<ActionLog>();
            MessageTemplates = new HashSet<MessageTemplate>();
        }

        public int Id { get; set; }
        public string Type { get; set; }

        public virtual ICollection<ActionLog> ActionsLog { get; set; }
        public virtual ICollection<MessageTemplate> MessageTemplates { get; set; }
    }
}