// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goc.Models
{
    using Goc.Models.Entities;

    public partial class ActionLog
    {
        public ActionLog()
        {
            Evidences = new HashSet<Evidence>();
            DuelRooms = new HashSet<DuelRoom>();
        }

        public long Id { get; set; }
        
        public int TeamCharacterId { get; set; }

        public int ActionTypeId { get; set; }

        public int? AffectedTeamId { get; set; }
        public DateTime DateTimeFrom { get; set; }
        public DateTime DateTimeTo { get; set; }
        public int? MissionId { get; set; }
        public int Coinks { get; set; }

        public virtual ActionType ActionType { get; set; }

        public virtual Membership TeamCharacter { get; set; }

        public virtual Mission Mission { get; set; }

        
        public virtual ICollection<Evidence> Evidences { get; set; }

        public virtual ICollection<DuelRoom> DuelRooms { get; set; }
    }
}