// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Goc.Models
{
    public partial class Character
    {
        public Character()
        {
            //ActionLog = new HashSet<ActionLog>();
            //Evidence = new HashSet<Evidence>();
            TeamsCharacters = new HashSet<Membership>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Story { get; set; }
        public string Attack { get; set; }
        public string Defense { get; set; }
        public string Bonus { get; set; }

        //public virtual ICollection<ActionLog> ActionLog { get; set; }
        //public virtual ICollection<Evidence> Evidence { get; set; }

        [JsonIgnore]
        public virtual ICollection<Membership> TeamsCharacters { get; set; }
    }
}