// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goc.Models
{
    public partial class Missions
    {
        public Missions()
        {
            ActionsLog = new HashSet<ActionsLog>();
            Campaign = new HashSet<Campaigns>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Story { get; set; }
        public string Instructions { get; set; }
        public int Coinks { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }

        public virtual ICollection<ActionsLog> ActionsLog { get; set; }

        public virtual ICollection<Campaigns> Campaign { get; set; }
    }
}