// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goc.Models
{
    public partial class TeamsCharacters
    {
        public int Id { get; set; }
        public int TeamId { get; set; }
        public int CharacterId { get; set; }
        public bool Email { get; set; }
        public int IsLeader { get; set; }

        public virtual Characters Character { get; set; }
        public virtual Teams Team { get; set; }
    }
}