// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goc.Models
{
    public partial class Team
    {
        public Team()
        {
            ActionsLog = new HashSet<ActionLog>();
            MessagesRecipientTeamNavigation = new HashSet<Message>();
            MessagesSenderTeamNavigation = new HashSet<Message>();
            TeamsCharacters = new HashSet<Membership>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int Coinks { get; set; }

        //TODO: Avoid load the image in all the queries
        public byte[]? Image { get; set; }

        public virtual ICollection<ActionLog> ActionsLog { get; set; }
        public virtual ICollection<Message> MessagesRecipientTeamNavigation { get; set; }
        public virtual ICollection<Message> MessagesSenderTeamNavigation { get; set; }
        public virtual ICollection<Membership> TeamsCharacters { get; set; }
    }
}