// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goc.Models
{
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.Serialization;
    using System.Text.Json.Serialization;

    [Table("Users")]
    public  class User
    {
        public User()
        {
            Mermberships = new HashSet<Membership>();
        }

        public int Id { get; set; }
        
        public string Upn { get; set; }
        
        public bool IsAdmin { get; set; }

        [JsonIgnore]
        public virtual ICollection<Membership> Mermberships { get; set; }
    }

    [Table("TeamsCharacters")]
    public partial class Membership
    {
        [Column("TeamCharacterId")]
        public int MembershipId { get; set; }


        public Membership()
        {
            ActionsLog = new HashSet<ActionLog>();
            Evidences = new HashSet<Evidence>();
        }

        public User? User { get; set; }

        [JsonIgnore]
        public virtual ICollection<ActionLog> ActionsLog { get; set; }

        [JsonIgnore]
        public virtual ICollection<Evidence> Evidences { get; set; }

        public int? UserId { get; set; }

        public int? TeamId { get; set; }

        public int? CharacterId { get; set; }

        public int CampaignId { get; set; }

        public bool IsLeader { get; set; }

        public bool PendingAproval { get; set; }

        public virtual Character? Character { get; set; }

        public virtual Team? Team { get; set; }
    }
}